// Realtime Cloud Messaging JavaScript Library
// Copyright 2014, Realtime.co
//
// Visit us at framework.realtime.co and learn more.
//
// Date: Fri Nov 14 2014 12:10 v2.1.20 (no beacon)

var IbtRealTimeSJType="IbtRealTimeSJ";function loadOrtcFactory(i,l){var a=new OrtcFactory(i);l(a,null)}function OrtcFactory(){this.createClient=function(){return new IbtRealTimeSJ}}
function OrtcError(i){this.code=i;switch(i){case 1:this.message="Was not possible to load the kaazing api";break;case 2:this.message="Was not possible to load the socket.io api";break;case 3:this.message="Is not possible to load more than one factory of each ORTC type";break;case 4:this.message="Unknown ORTC type";break;case 5:this.message="Pusher key is not defined";break;case 6:this.message="Was not possible to load the pusher api";break;default:this.message="Unknown error"}}
String.prototype.ortcTreatUrl=function(){var i=this;i&&(i=i.replace(/\s+/g,""),"/"==i.charAt(i.length-1)&&(i=i.substring(0,i.length-1)));return i};function ortcIsValidUrl(i){return/^\s*(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?\s*$/.exec(i)?!0:!1}function ortcIsValidInput(i){return/^[\w-:\/\.]*$/.exec(i)?!0:!1}function ortcIsValidBoolean(i){return/^(true|false|0|1)$/.exec(i)?!0:!1}function ortcIsFunction(i){return"function"==typeof i?!0:!1}
function ortcIsString(i){return"string"==typeof i?!0:!1}var _qevents=_qevents||[],JSON;JSON||(JSON={});
(function(){function i(a,A){var p,t,r,h,q=k,m,n=A[a];n&&"object"==typeof n&&"function"==typeof n.toJSON&&(n=n.toJSON(a));"function"==typeof v&&(n=v.call(A,a,n));switch(typeof n){case "string":return l(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";k+=z;m=[];if("[object Array]"===Object.prototype.toString.apply(n)){h=n.length;for(p=0;p<h;p+=1)m[p]=i(p,n)||"null";r=0===m.length?"[]":k?"[\n"+k+m.join(",\n"+k)+"\n"+q+"]":
"["+m.join(",")+"]";k=q;return r}if(v&&"object"==typeof v){h=v.length;for(p=0;p<h;p+=1)"string"==typeof v[p]&&(t=v[p],r=i(t,n),r&&m.push(l(t)+(k?": ":":")+r))}else for(t in n)Object.prototype.hasOwnProperty.call(n,t)&&(r=i(t,n),r&&m.push(l(t)+(k?": ":":")+r));r=0===m.length?"{}":k?"{\n"+k+m.join(",\n"+k)+"\n"+q+"}":"{"+m.join(",")+"}";k=q;return r}}function l(a){s.lastIndex=0;return s.test(a)?'"'+a.replace(s,function(a){var d=F[a];return"string"==typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function a(a){return 10>a?"0"+a:a}"use strict";"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var y=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
s=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,z,F={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;"function"!=typeof JSON.stringify&&(JSON.stringify=function(a,l,p){var t;z=k="";if("number"==typeof p)for(t=0;t<p;t+=1)z+=" ";else"string"==typeof p&&(z=p);v=l;if(!l||"function"==typeof l||"object"==typeof l&&"number"==typeof l.length)return i("",{"":a});throw Error("JSON.stringify");});"function"!=
typeof JSON.parse&&(JSON.parse=function(a,i){function l(a,d){var k,m,n=a[d];if(n&&"object"==typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(m=l(n,k),void 0!==m?n[k]=m:delete n[k]);return i.call(a,d,n)}var k,a=String(a);y.lastIndex=0;y.test(a)&&(a=a.replace(y,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return k=eval("("+a+")"),"function"==typeof i?l({"":k},""):k;throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var i=document,l=window,a={},y=function(){};y.prototype.addEventListener=function(j,e){this._listeners||(this._listeners={});j in this._listeners||(this._listeners[j]=[]);var c=this._listeners[j];-1===a.arrIndexOf(c,e)&&c.push(e)};y.prototype.removeEventListener=function(j,e){if(this._listeners&&j in this._listeners){var c=this._listeners[j],b=a.arrIndexOf(c,e);-1!==b&&(1<c.length?this._listeners[j]=c.slice(0,b).concat(c.slice(b+1)):delete this._listeners[j])}};y.prototype.dispatchEvent=
function(j){var a=j.type,c=Array.prototype.slice.call(arguments,0);this["on"+a]&&this["on"+a].apply(this,c);if(this._listeners&&a in this._listeners)for(var b=0;b<this._listeners[a].length;b++)this._listeners[a][b].apply(this,c)};var s=function(j,a){this.type=j;if("undefined"!=typeof a)for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c])};s.prototype.toString=function(){var j=[],a;for(a in this)if(this.hasOwnProperty(a)){var c=this[a];"function"==typeof c&&(c="[function]");j.push(a+"="+c)}return"SimpleEvent("+
j.join(", ")+")"};var k=function(a){this.events=a||[]};k.prototype.emit=function(j){var e=Array.prototype.slice.call(arguments,1);!this.nuked&&this["on"+j]&&this["on"+j].apply(this,e);-1===a.arrIndexOf(this.events,j)&&a.log("Event "+JSON.stringify(j)+" not listed "+JSON.stringify(this.events)+" in "+this)};k.prototype.nuke=function(){this.nuked=!0;for(var a=0;a<this.events.length;a++)delete this[this.events[a]]};a.random_string=function(a,e){var e=e||37,c,b=[];for(c=0;c<a;c++)b.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*
e),1));return b.join("")};a.random_number=function(a){return Math.floor(Math.random()*a)};a.random_number_string=function(j){var e=(""+(j-1)).length;return(Array(e+1).join("0")+a.random_number(j)).slice(-e)};a.getOrigin=function(a){return(a+"/").split("/").slice(0,3).join("/")};a.isLocalUrl=function(a){var e=l.location.href.split("/").slice(0,3).join("/");return a.slice(0,e.length)===e};a.objectExtend=function(a,e){for(var c in e)e.hasOwnProperty(c)&&(a[c]=e[c]);return a};a.polluteGlobalNamespace=
function(){"_jp"in l||(l._jp={})};a.closeFrame=function(a,e){return"c"+JSON.stringify([a,e])};a.userSetCode=function(a){return 1E3===a||3E3<=a&&4999>=a};a.countRTO=function(a){var e;return 100<a?e=3*a:e=a+200,e};a.log=function(){l.console&&console.log&&console.log.apply&&console.log.apply(console,arguments)};a.bind=function(a,e){return a.bind?a.bind(e):function(){return a.apply(e,arguments)}};a.amendUrl=function(a){var e=i.location;if(!a)throw Error("Wrong url for SockJS");return 0===a.indexOf("//")&&
(a=e.protocol+a),0===a.indexOf("/")&&(a=e.protocol+"//"+e.host+a),a=a.replace(/[/]+$/,""),a};a.arrIndexOf=function(a,e){for(var c=0;c<a.length;c++)if(a[c]===e)return c;return-1};a.arrSkip=function(j,e){var c=a.arrIndexOf(j,e);return-1===c?j.slice():j.slice(0,c).concat(j.slice(c+1))};a.isArray=Array.isArray||function(a){return 0<={}.toString.call(a).indexOf("Array")};a.delay=function(a,e){return"function"==typeof a&&(e=a,a=0),setTimeout(e,a)};var z=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
F={"\x00":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\b":"\\b","\t":"\\t","\n":"\\n","\x0B":"\\u000b","\f":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010","\u0011":"\\u0011","\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b","\u001c":"\\u001c",
"\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","\u007f":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082","\u0083":"\\u0083","\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089","\u008a":"\\u008a","\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094","\u0095":"\\u0095",
"\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d","\u009e":"\\u009e","\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603","\u0604":"\\u0604","\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a","\u202b":"\\u202b",
"\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063","\u2064":"\\u2064","\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a","\u206b":"\\u206b","\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4","\ufff5":"\\ufff5",
"\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd","\ufffe":"\\ufffe","\uffff":"\\uffff"},v=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
d,A=JSON&&JSON.stringify||function(a){return z.lastIndex=0,z.test(a)&&(a=a.replace(z,function(a){return F[a]})),'"'+a+'"'};a.quote=function(a){a=A(a);v.lastIndex=0;if(v.test(a)){if(!d){var e,c={},b=[];for(e=0;65536>e;e++)b.push(String.fromCharCode(e));d=(v.lastIndex=0,b.join("").replace(v,function(b){return c[b]="\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4),""}),v.lastIndex=0,c)}a=a.replace(v,function(c){return d[c]})}return a};var p="websocket xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile xdr-polling xhr-polling iframe-xhr-polling jsonp-polling".split(" ");
a.probeProtocols=function(){for(var a={},e=0;e<p.length;e++){var c=p[e];a[c]=h[c]&&h[c].enabled()}return a};a.detectProtocols=function(a,e,c){var b={},f=[];e||(e=p);for(var g=0;g<e.length;g++){var x=e[g];b[x]=a[x]}var d=function(c){var a=c.shift();b[a]?f.push(a):0<c.length&&d(c)};return!1!==c.websocket&&d(["websocket"]),b["xdr-streaming"]&&!c.cookie_needed?f.push("xdr-streaming"):d(["xhr-streaming","iframe-eventsource","iframe-htmlfile"]),b["xdr-polling"]&&!c.cookie_needed?f.push("xdr-polling"):d(["xhr-polling",
"iframe-xhr-polling","jsonp-polling"]),f};a.createHook=function(){var j="a"+a.random_string(8);if(!("_sockjs_global"in l)){var e={};l._sockjs_global=function(c){return c in e||(e[c]={id:c,del:function(){delete e[c]}}),e[c]}}return l._sockjs_global(j)};a.attachMessage=function(j){a.attachEvent("message",j)};a.attachEvent=function(a,e){"undefined"!=typeof l.addEventListener?l.addEventListener(a,e,!1):(i.attachEvent("on"+a,e),l.attachEvent("on"+a,e))};a.detachMessage=function(j){a.detachEvent("message",
j)};a.detachEvent=function(a,e){"undefined"!=typeof l.addEventListener?l.removeEventListener(a,e,!1):(i.detachEvent("on"+a,e),l.detachEvent("on"+a,e))};var t={};a.unload_add=function(j){var e=a.random_string(8);return t[e]=j,e};a.unload_del=function(a){a in t&&delete t[a]};a.attachEvent("unload",function(){for(var a in t)t[a]()});a.createIframe=function(j,e){var c=i.createElement("iframe"),b,f=function(){clearTimeout(b);try{c.onload=null}catch(a){}c.onerror=null},g=function(){c&&(f(),c.src="about:blank",
setTimeout(function(){c&&c.parentNode.removeChild(c);c=null},0),a.detachEvent("unload",g))};return c.src=j,c.style.display="none",c.style.position="absolute",c.onerror=function(){c&&(g(),e("onerror"))},c.onload=function(){clearTimeout(b);b=setTimeout(function(){c&&(g(),e("onload timeout"))},2E3)},i.body.appendChild(c),b=setTimeout(function(){c&&(g(),e("timeout"))},5E3),a.attachEvent("unload",g),{iframe:c,cleanup:g,loaded:f}};a.createHtmlfile=function(j,e){var c=new ActiveXObject("htmlfile"),b,f,g=
function(){clearTimeout(b)},x=function(){if(c){g();a.detachEvent("unload",x);try{f.src="about:blank"}catch(b){}f.parentNode.removeChild(f);f=c=null;CollectGarbage()}};c.open();c.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');c.close();c.parentWindow._jp=l._jp;var d=c.createElement("div");return c.body.appendChild(d),f=c.createElement("iframe"),d.appendChild(f),f.src=j,b=setTimeout(function(){c&&(x(),e("timeout"))},5E3),a.attachEvent("unload",x),{iframe:f,cleanup:x,
loaded:g}};var r=a.XHRObject=function(j,e,c){var b=this;a.delay(function(){b._start(j,e,c)})};r.prototype=new k(["chunk","finish"]);r.prototype._start=function(j,e,c){var b=this;if(l.ActiveXObject){e+=(-1===e.indexOf("?")?"?":"&")+"t="+ +new Date;try{b.xhr=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){}}b.xhr||(b.xhr=new XMLHttpRequest);b.unload_ref=a.unload_add(function(){b._cleanup(!0)});try{b.xhr.open(j,e,!0)}catch(g){b.emit("finish",0,"");b._cleanup();return}"withCredentials"in b.xhr&&(b.xhr.withCredentials=
"true");b.xhr.onreadystatechange=function(){if(b.xhr){var c=b.xhr;switch(c.readyState){case 3:try{b.emit("chunk",c.status,c.responseText)}catch(a){}break;case 4:b.emit("finish",c.status,c.responseText),b._cleanup(!1)}}};b.xhr.send(c)};r.prototype._cleanup=function(j){if(this.xhr){a.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(j)try{this.xhr.abort()}catch(e){}this.unload_ref=this.xhr=null}};r.prototype.close=function(){this.nuke();this._cleanup(!0)};r=a.XDRObject=function(j,
e,c){var b=this;a.delay(function(){b._start(j,e,c)})};r.prototype=new k(["chunk","finish"]);r.prototype._start=function(j,e,c){var b=this,f=new XDomainRequest,e=e+((-1===e.indexOf("?")?"?":"&")+"t="+ +new Date),g=f.ontimeout=f.onerror=function(){b.emit("finish",0,"");b._cleanup(!1)};f.onprogress=function(){b.emit("chunk",200,f.responseText)};f.onload=function(){b.emit("finish",200,f.responseText);b._cleanup(!1)};b.xdr=f;b.unload_ref=a.unload_add(function(){b._cleanup(!0)});try{b.xdr.open(j,e),b.xdr.send(c)}catch(x){g()}};
r.prototype._cleanup=function(j){if(this.xdr){a.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(j)try{this.xdr.abort()}catch(e){}this.unload_ref=this.xdr=null}};r.prototype.close=function(){this.nuke();this._cleanup(!0)};a.isXHRCorsCapable=function(){return l.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest?1:l.XDomainRequest?2:w.enabled()?3:4};var h=function(j,e,c){var b=this,f;b._options={devel:!1,debug:!1,protocols_whitelist:[],
info:void 0,rtt:void 0};c&&a.objectExtend(b._options,c);b._base_url=a.amendUrl(j);b._server=b._options.server||a.random_number_string(1E3);b._options.protocols_whitelist&&b._options.protocols_whitelist.length?f=b._options.protocols_whitelist:("string"==typeof e&&0<e.length?f=[e]:a.isArray(e)?f=e:f=null,f&&b._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.'));b._protocols=[];b.protocol=null;b.readyState=h.CONNECTING;
O(b._base_url).onfinish=function(c,a){c?(b._options.info&&(c=b._options.info),b._options.rtt&&(a=b._options.rtt),b._applyInfo(c,a,f),b._didClose()):b._didClose(1002,"Can't connect to server",!0)}};h.prototype=new y;h.version="0.2.1";h.CONNECTING=0;h.OPEN=1;h.CLOSING=2;h.CLOSED=3;h.prototype._debug=function(){this._options.debug&&a.log.apply(a,arguments)};h.prototype._dispatchOpen=function(){this.readyState===h.CONNECTING?(this._transport_tref&&(clearTimeout(this._transport_tref),this._transport_tref=
null),this.readyState=h.OPEN,this.dispatchEvent(new s("open"))):this._didClose(1006,"Server lost session")};h.prototype._dispatchMessage=function(a){this.readyState===h.OPEN&&this.dispatchEvent(new s("message",{data:a}))};h.prototype._dispatchHeartbeat=function(){this.readyState===h.OPEN&&this.dispatchEvent(new s("heartbeat",{}))};h.prototype._didClose=function(j,e,c){var b=this;if(b.readyState!==h.CONNECTING&&b.readyState!==h.OPEN&&b.readyState!==h.CLOSING)throw Error("INVALID_STATE_ERR");b._transport&&
b._transport.doCleanup();b._transport=null;var f=new s("close",{code:j,reason:e,wasClean:a.userSetCode(j)});if(!a.userSetCode(j)&&b.readyState===h.CONNECTING&&!c){if(b._try_next_protocol(f))return;f=new s("close",{code:2E3,reason:"All transports failed",wasClean:!1,last_event:f})}b.readyState=h.CLOSED;a.delay(function(){b.dispatchEvent(f)})};h.prototype._didMessage=function(a){switch(a.slice(0,1)){case "o":this._dispatchOpen();break;case "a":for(var a=JSON.parse(a.slice(1)||"[]"),e=0;e<a.length;e++)this._dispatchMessage(a[e]);
break;case "m":a=JSON.parse(a.slice(1)||"null");this._dispatchMessage(a);break;case "c":a=JSON.parse(a.slice(1)||"[]");this._didClose(a[0],a[1]);break;case "h":this._dispatchHeartbeat()}};h.prototype._try_next_protocol=function(j){var e=this;e.protocol&&(e._debug("Closed transport:",e.protocol,""+j),e.protocol=null);for(e._transport_tref&&(clearTimeout(e._transport_tref),e._transport_tref=null);;){j=e.protocol=e._protocols.shift();if(!j)return!1;if(h[j]&&!0===h[j].need_body&&!i.body)return e._protocols.unshift(j),
e.protocol="waiting-for-load",a.attachEvent("load",function(){e._try_next_protocol()}),!0;if(!h[j]||!h[j].enabled(e._options))e._debug("Skipping transport:",j);else{e._transport_tref=a.delay((e._options.rto||0)*(h[j].roundTrips||1)||5E3,function(){e.readyState===h.CONNECTING&&e._didClose(2007,"Transport timeouted")});var c=a.random_string(8),c=e._base_url+"/"+e._server+"/"+c;return e._debug("Opening transport:",j," url:"+c," RTO:"+e._options.rto),e._transport=new h[j](e,c,e._base_url),!0}}};h.prototype.close=
function(j,e){if(j&&!a.userSetCode(j))throw Error("INVALID_ACCESS_ERR");return this.readyState!==h.CONNECTING&&this.readyState!==h.OPEN?!1:(this.readyState=h.CLOSING,this._didClose(j||1E3,e||"Normal closure"),!0)};h.prototype.send=function(j){if(this.readyState===h.CONNECTING)throw Error("INVALID_STATE_ERR");return this.readyState===h.OPEN&&this._transport.doSend(a.quote(""+j)),!0};h.prototype._applyInfo=function(j,e,c){this._options.info=j;this._options.rtt=e;this._options.rto=a.countRTO(e);e=a.probeProtocols();
this._protocols=a.detectProtocols(e,c,j)};r=h.websocket=function(j,e){var c=this,b=e+"/websocket";"https"===b.slice(0,5)?b="wss"+b.slice(5):b="ws"+b.slice(4);c.ri=j;c.url=b;c.ws=new (l.WebSocket||l.MozWebSocket)(c.url);c.ws.onmessage=function(a){c.ri._didMessage(a.data)};c.unload_ref=a.unload_add(function(){c.ws.close()});c.ws.onclose=function(){c.ri._didMessage(a.closeFrame(1006,"WebSocket connection broken"))}};r.prototype.doSend=function(a){this.ws.send(a)};r.prototype.doCleanup=function(){var j=
this.ws;j&&(j.onmessage=j.onclose=null,j.close(),a.unload_del(this.unload_ref),this.unload_ref=this.ri=this.ws=null)};r.enabled=function(){return!!l.WebSocket||!!l.MozWebSocket};var q=function(){};q.prototype.send_constructor=function(a){this.send_buffer=[];this.sender=a};q.prototype.doSend=function(a){this.send_buffer.push(a);this.send_stop||this.send_schedule()};q.prototype.send_schedule_wait=function(){var j=this,e;j.send_stop=function(){j.send_stop=null;clearTimeout(e)};e=a.delay(25,function(){j.send_stop=
null;j.send_schedule()})};q.prototype.send_schedule=function(){var a=this;if(0<a.send_buffer.length){var e="["+a.send_buffer.join(",")+"]";a.send_stop=a.sender(a.trans_url,e,function(){a.send_stop=null;a.send_schedule_wait()});a.send_buffer=[]}};q.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var m=function(j,e,c){if(!("_send_form"in this)){var b=this._send_form=i.createElement("form"),f=this._send_area=i.createElement("textarea");f.name="d";b.style.display=
"none";b.style.position="absolute";b.method="POST";b.enctype="application/x-www-form-urlencoded";b.acceptCharset="UTF-8";b.appendChild(f);i.body.appendChild(b)}var b=this._send_form,f=this._send_area,g="a"+a.random_string(8);b.target=g;b.action=j+"/jsonp_send?i="+g;var x;try{x=i.createElement('<iframe name="'+g+'">')}catch(d){x=i.createElement("iframe"),x.name=g}x.id=g;b.appendChild(x);x.style.display="none";try{f.value=e}catch(u){alert("Your browser is seriously broken. Go home! "+u.message)}b.submit();
var h=function(){x.onerror&&(x.onreadystatechange=x.onerror=x.onload=null,a.delay(500,function(){x.parentNode.removeChild(x);x=null}),f.value=null,c())};return x.onerror=x.onload=h,x.onreadystatechange=function(){"complete"==x.readyState&&h()},h},n=function(a){return function(e,c,b){return(new a("POST",e+"/xhr_send",c)).onfinish=function(c){b(c)},function(c){b(0,c)}}},r=h["jsonp-polling"]=function(j,e){a.polluteGlobalNamespace();this.ri=j;this.trans_url=e;this.send_constructor(m);this._schedule_recv()};
r.prototype=new q;r.prototype._schedule_recv=function(){var j=this,e=j.trans_url+"/jsonp",c="a"+a.random_string(6),e=e+"?c="+escape("_jp."+c),b=function(a){delete l._jp[c];j._recv_stop=null;a&&(j._is_closing||j.ri._didMessage(a));j._is_closing||j._schedule_recv()},f,g=i.createElement("script"),x,d=function(c){x&&(x.parentNode.removeChild(x),x=null);g&&(clearTimeout(f),g.parentNode.removeChild(g),g.onreadystatechange=g.onerror=g.onload=g.onclick=null,g=null,b(c),b=null)},u=!1,h=null;g.id="a"+a.random_string(8);
g.src=e;g.type="text/javascript";g.charset="UTF-8";g.onerror=function(){h||(h=setTimeout(function(){u||d(a.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};g.onload=function(){d(a.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};g.onreadystatechange=function(){if(/loaded|closed/.test(g.readyState)){if(g&&g.htmlFor&&g.onclick){u=!0;try{g.onclick()}catch(c){}}g&&d(a.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if("undefined"==typeof g.async&&
i.attachEvent)if(/opera/i.test(navigator.userAgent))x=i.createElement("script"),x.text="try{var a = document.getElementById('"+g.id+"'); if(a)a.onerror();}catch(x){};",g.async=x.async=!1;else{try{g.htmlFor=g.id,g.event="onclick"}catch(k){}g.async=!0}"undefined"!=typeof g.async&&(g.async=!0);f=setTimeout(function(){d(a.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);e=i.getElementsByTagName("head")[0];e=(e.insertBefore(g,e.firstChild),x&&e.insertBefore(x,e.firstChild),d);l._jp[c]=
e;j._recv_stop=function(){l._jp[c]&&l._jp[c](a.closeFrame(1E3,"JSONP user aborted read"))}};r.enabled=function(){return!0};r.need_body=!0;r.prototype.doCleanup=function(){this._is_closing=!0;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};r=function(){};r.prototype=new q;r.prototype.run=function(a,e,c,b,f){this.ri=a;this.trans_url=e;this.send_constructor(n(f));this.poll=new J(a,b,e+c,f)};r.prototype.doCleanup=function(){this.poll&&(this.poll.abort(),this.poll=
null)};var C=h["xhr-streaming"]=function(d,e){this.run(d,e,"/xhr_streaming",G,a.XHRObject)};C.prototype=new r;C.enabled=function(){return l.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest};C.roundTrips=2;q=h["xdr-streaming"]=function(d,e){this.run(d,e,"/xhr_streaming",G,a.XDRObject)};q.prototype=new r;q.enabled=function(){return!!l.XDomainRequest};q.roundTrips=2;var H=h["xhr-polling"]=function(d,e){this.run(d,e,"/xhr",G,a.XHRObject)};H.prototype=new r;H.enabled=C.enabled;H.roundTrips=2;C=h["xdr-polling"]=
function(d,e){this.run(d,e,"/xhr",G,a.XDRObject)};C.prototype=new r;C.enabled=q.enabled;C.roundTrips=2;var w=function(){};w.prototype.i_constructor=function(d,e,c){var b=this;b.ri=d;b.origin=a.getOrigin(c);b.base_url=c;b.trans_url=e;d=c+"/iframe.html";b.ri._options.devel&&(d+="?t="+ +new Date);b.window_id=a.random_string(8);d+="#"+b.window_id;b.iframeObj=a.createIframe(d,function(c){b.ri._didClose(1006,"Unable to load an iframe ("+c+")")});b.onmessage_cb=a.bind(b.onmessage,b);a.attachMessage(b.onmessage_cb)};
w.prototype.doCleanup=function(){if(this.iframeObj){a.detachMessage(this.onmessage_cb);try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(d){}this.iframeObj.cleanup();this.onmessage_cb=this.iframeObj=this.iframeObj=null}};w.prototype.onmessage=function(a){if(a.origin===this.origin){var e=a.data.slice(0,8),c=a.data.slice(8,9),a=a.data.slice(9);if(e===this.window_id)switch(c){case "s":this.iframeObj.loaded();this.postMessage("s",JSON.stringify([h.version,this.protocol,this.trans_url,
this.base_url]));break;case "t":this.ri._didMessage(a)}}};w.prototype.postMessage=function(a,e){this.iframeObj.iframe.contentWindow.postMessage(this.window_id+a+(e||""),this.origin)};w.prototype.doSend=function(a){this.postMessage("m",a)};w.enabled=function(){var a=navigator&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("Konqueror");return("function"==typeof l.postMessage||"object"==typeof l.postMessage)&&!a};var M,B=function(d,e){parent!==l?parent.postMessage(M+d+(e||""),"*"):a.log("Can't postMessage, no parent window.",
d,e)},D=function(){};D.prototype._didClose=function(d,e){B("t",a.closeFrame(d,e))};D.prototype._didMessage=function(a){B("t",a)};D.prototype._doSend=function(a){this._transport.doSend(a)};D.prototype._doCleanup=function(){this._transport.doCleanup()};h.bootstrap_iframe=function(){var d;M=i.location.hash.slice(1);a.attachMessage(function(e){if(e.source===parent){var c=e.data.slice(0,8),b=e.data.slice(8,9),e=e.data.slice(9);if(c===M)switch(b){case "s":var f=JSON.parse(e),c=f[0],b=f[1],e=f[2],f=f[3];
c!==h.version&&a.log('Incompatibile SockJS! Main site uses: "'+c+'", the iframe: "'+h.version+'".');if(!a.isLocalUrl(e)||!a.isLocalUrl(f)){a.log("Can't connect to different domain from within an iframe. ("+JSON.stringify([l.location.href,e,f])+")");break}d=new D;d._transport=new D[b](d,e,f);break;case "m":d._doSend(e);break;case "c":d&&d._doCleanup(),d=null}}});B("s")};var I=function(d,e){var c=this;a.delay(function(){c.doXhr(d,e)})};I.prototype=new k(["finish"]);I.prototype.doXhr=function(d,e){var c=
this,b=(new Date).getTime(),f=new e("GET",d+"/info",null),g=a.delay(8E3,function(){f.ontimeout()});f.onfinish=function(a,f){clearTimeout(g);g=null;if(200===a){var e=(new Date).getTime()-b,d=JSON.parse(f);"object"!=typeof d&&(d={});c.emit("finish",d,e)}else c.emit("finish")};f.ontimeout=function(){f.close();c.emit("finish")}};var E=function(d){var e=this,c=function(){var c=new w;c.protocol="w-iframe-info-receiver";var a=function(a){"string"==typeof a&&"m"===a.substr(0,1)?(a=JSON.parse(a.substr(1)),
e.emit("finish",a[0],a[1])):e.emit("finish");c.doCleanup();c=null};c.i_constructor({_options:{},_didClose:a,_didMessage:a},d,d)};i.body?c():a.attachEvent("load",c)};E.prototype=new k(["finish"]);var K=function(){var d=this;a.delay(function(){d.emit("finish",{},2E3)})};K.prototype=new k(["finish"]);var O=function(d){if(a.isLocalUrl(d))return new I(d,a.XHRObject);switch(a.isXHRCorsCapable()){case 1:return new I(d,a.XHRObject);case 2:return new I(d,a.XDRObject);case 3:return new E(d);default:return new K}};
(D["w-iframe-info-receiver"]=function(d,e,c){(new I(c,a.XHRObject)).onfinish=function(c,a){d._didMessage("m"+JSON.stringify([c,a]));d._didClose()}}).prototype.doCleanup=function(){};k=h["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};k.prototype=new w;k.enabled=function(){return"EventSource"in l&&w.enabled()};k.need_body=!0;k.roundTrips=3;(D["w-iframe-eventsource"]=function(d,e){this.run(d,e,"/eventsource",P,a.XHRObject)}).prototype=
new r;k=h["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};k.prototype=new w;k.enabled=function(){return l.XMLHttpRequest&&w.enabled()};k.need_body=!0;k.roundTrips=3;(D["w-iframe-xhr-polling"]=function(d,e){this.run(d,e,"/xhr",G,a.XHRObject)}).prototype=new r;k=h["iframe-htmlfile"]=function(){this.protocol="w-iframe-htmlfile";this.i_constructor.apply(this,arguments)};k.prototype=new w;k.enabled=function(){return w.enabled()};k.need_body=
!0;k.roundTrips=3;(D["w-iframe-htmlfile"]=function(d,e){this.run(d,e,"/htmlfile",N,a.XHRObject)}).prototype=new r;var J=function(a,d,c,b){this.ri=a;this.Receiver=d;this.recv_url=c;this.AjaxObject=b;this._scheduleRecv()};J.prototype._scheduleRecv=function(){var a=this,d=a.poll=new a.Receiver(a.recv_url,a.AjaxObject);d.onmessage=function(c){a.ri._didMessage(c.data)};d.onclose=function(c){a.poll=d=d.onmessage=d.onclose=null;a.poll_is_closing||("permanent"===c.reason?a.ri._didClose(1006,"Polling error ("+
c.reason+")"):a._scheduleRecv())}};J.prototype.abort=function(){this.poll_is_closing=!0;this.poll&&this.poll.abort()};var P=function(d){var e=this,c=new EventSource(d);c.onmessage=function(c){e.dispatchEvent(new s("message",{data:unescape(c.data)}))};e.es_close=c.onerror=function(b,f){var g=f?"user":2!==c.readyState?"network":"permanent";e.es_close=c.onmessage=c.onerror=null;c.close();c=null;a.delay(200,function(){e.dispatchEvent(new s("close",{reason:g}))})}};P.prototype=new y;P.prototype.abort=
function(){this.es_close&&this.es_close({},!0)};var L,N=function(d){var e=this;a.polluteGlobalNamespace();e.id="a"+a.random_string(6,26);d+=(-1===d.indexOf("?")?"?":"&")+"c="+escape("_jp."+e.id);if(void 0===L)if("ActiveXObject"in l)try{L=!!new ActiveXObject("htmlfile")}catch(c){}else L=!1;var b=L?a.createHtmlfile:a.createIframe,f;l._jp[e.id]={start:function(){f.loaded()},message:function(c){e.dispatchEvent(new s("message",{data:c}))},stop:function(){e.iframe_close({},"network")}};e.iframe_close=function(c,
a){f.cleanup();e.iframe_close=f=null;delete l._jp[e.id];e.dispatchEvent(new s("close",{reason:a}))};f=b(d,function(){e.iframe_close({},"permanent")})};N.prototype=new y;N.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var G=function(a,d){var c=this,b=0;c.xo=new d("POST",a,null);c.xo.onchunk=function(a,g){if(200===a)for(;;){var d=g.slice(b),e=d.indexOf("\n");if(-1===e)break;b+=e+1;d=d.slice(0,e);c.dispatchEvent(new s("message",{data:d}))}};c.xo.onfinish=function(a,b){c.xo.onchunk(a,
b);c.xo=null;c.dispatchEvent(new s("close",{reason:200===a?"network":"permanent"}))}};return G.prototype=new y,G.prototype.abort=function(){this.xo&&(this.xo.close(),this.dispatchEvent(new s("close",{reason:"user"})),this.xo=null)},h.getUtils=function(){return a},h.getIframeTransport=function(){return w},h}();"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);JSON||(JSON={});
(function(){function i(a,s){var p,t,r,h,q=k,m,n=s[a];n&&"object"==typeof n&&"function"==typeof n.toJSON&&(n=n.toJSON(a));"function"==typeof v&&(n=v.call(s,a,n));switch(typeof n){case "string":return l(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";k+=z;m=[];if("[object Array]"===Object.prototype.toString.apply(n)){h=n.length;for(p=0;p<h;p+=1)m[p]=i(p,n)||"null";r=0===m.length?"[]":k?"[\n"+k+m.join(",\n"+k)+"\n"+q+"]":
"["+m.join(",")+"]";k=q;return r}if(v&&"object"==typeof v){h=v.length;for(p=0;p<h;p+=1)"string"==typeof v[p]&&(t=v[p],r=i(t,n),r&&m.push(l(t)+(k?": ":":")+r))}else for(t in n)Object.prototype.hasOwnProperty.call(n,t)&&(r=i(t,n),r&&m.push(l(t)+(k?": ":":")+r));r=0===m.length?"{}":k?"{\n"+k+m.join(",\n"+k)+"\n"+q+"}":"{"+m.join(",")+"}";k=q;return r}}function l(a){s.lastIndex=0;return s.test(a)?'"'+a.replace(s,function(a){var d=F[a];return"string"==typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function a(a){return 10>a?"0"+a:a}"use strict";"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var y=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
s=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,z,F={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;"function"!=typeof JSON.stringify&&(JSON.stringify=function(a,l,p){var t;z=k="";if("number"==typeof p)for(t=0;t<p;t+=1)z+=" ";else"string"==typeof p&&(z=p);v=l;if(!l||"function"==typeof l||"object"==typeof l&&"number"==typeof l.length)return i("",{"":a});throw Error("JSON.stringify");});"function"!=
typeof JSON.parse&&(JSON.parse=function(a,i){function l(a,d){var k,m,n=a[d];if(n&&"object"==typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(m=l(n,k),void 0!==m?n[k]=m:delete n[k]);return i.call(a,d,n)}var k,a=String(a);y.lastIndex=0;y.test(a)&&(a=a.replace(y,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return k=eval("("+a+")"),"function"==typeof i?l({"":k},""):k;throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var i=document,l=window,a={},y=function(){};y.prototype.addEventListener=function(c,b){this._listeners||(this._listeners={});c in this._listeners||(this._listeners[c]=[]);var f=this._listeners[c];-1===a.arrIndexOf(f,b)&&f.push(b)};y.prototype.removeEventListener=function(c,b){if(this._listeners&&c in this._listeners){var f=this._listeners[c],g=a.arrIndexOf(f,b);-1!==g&&(1<f.length?this._listeners[c]=f.slice(0,g).concat(f.slice(g+1)):delete this._listeners[c])}};y.prototype.dispatchEvent=
function(c){var a=c.type,f=Array.prototype.slice.call(arguments,0);this["on"+a]&&this["on"+a].apply(this,f);if(this._listeners&&a in this._listeners)for(var g=0;g<this._listeners[a].length;g++)this._listeners[a][g].apply(this,f)};var s=function(c,a){this.type=c;if("undefined"!==typeof a)for(var f in a)a.hasOwnProperty(f)&&(this[f]=a[f])};s.prototype.toString=function(){var a=[],b;for(b in this)if(this.hasOwnProperty(b)){var f=this[b];"function"===typeof f&&(f="[function]");a.push(b+"="+f)}return"SimpleEvent("+
a.join(", ")+")"};var k=function(a){this.events=a||[]};k.prototype.emit=function(c){var b=Array.prototype.slice.call(arguments,1);!this.nuked&&this["on"+c]&&this["on"+c].apply(this,b);-1===a.arrIndexOf(this.events,c)&&a.log("Event "+JSON.stringify(c)+" not listed "+JSON.stringify(this.events)+" in "+this)};k.prototype.nuke=function(){this.nuked=!0;for(var a=0;a<this.events.length;a++)delete this[this.events[a]]};a.random_string=function(a,b){var b=b||37,f,g=[];for(f=0;f<a;f++)g.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*
b),1));return g.join("")};a.random_number=function(a){return Math.floor(Math.random()*a)};a.random_number_string=function(c){var b=(""+(c-1)).length;return(Array(b+1).join("0")+a.random_number(c)).slice(-b)};a.getOrigin=function(a){return(a+"/").split("/").slice(0,3).join("/")};a.isSameOriginUrl=function(a,b){b||(b=l.location.href);return a.split("/").slice(0,3).join("/")===b.split("/").slice(0,3).join("/")};a.getParentDomain=function(a){return/^[0-9.]*$/.test(a)||/^\[/.test(a)||!/[.]/.test(a)?a:
a.split(".").slice(1).join(".")};a.objectExtend=function(a,b){for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f]);return a};a.polluteGlobalNamespace=function(){"_jp"in l||(l._jp={})};a.closeFrame=function(a,b){return"c"+JSON.stringify([a,b])};a.userSetCode=function(a){return 1E3===a||3E3<=a&&4999>=a};a.countRTO=function(a){return 100<a?3*a:a+200};a.log=function(){l.console&&console.log&&console.log.apply&&console.log.apply(console,arguments)};a.bind=function(a,b){return a.bind?a.bind(b):function(){return a.apply(b,
arguments)}};a.flatUrl=function(a){return-1===a.indexOf("?")&&-1===a.indexOf("#")};a.amendUrl=function(c){var b=i.location;if(!c)throw Error("Wrong url for SockJS");if(!a.flatUrl(c))throw Error("Only basic urls are supported in SockJS");0===c.indexOf("//")&&(c=b.protocol+c);0===c.indexOf("/")&&(c=b.protocol+"//"+b.host+c);return c.replace(/[/]+$/,"")};a.arrIndexOf=function(a,b){for(var f=0;f<a.length;f++)if(a[f]===b)return f;return-1};a.arrSkip=function(c,b){var f=a.arrIndexOf(c,b);return-1===f?c.slice():
c.slice(0,f).concat(c.slice(f+1))};a.isArray=Array.isArray||function(a){return 0<={}.toString.call(a).indexOf("Array")};a.delay=function(a,b){"function"===typeof a&&(b=a,a=0);return setTimeout(b,a)};var z=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,F={"\x00":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\b":"\\b","\t":"\\t",
"\n":"\\n","\x0B":"\\u000b","\f":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010","\u0011":"\\u0011","\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b","\u001c":"\\u001c","\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","\u007f":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082","\u0083":"\\u0083",
"\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089","\u008a":"\\u008a","\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094","\u0095":"\\u0095","\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d","\u009e":"\\u009e",
"\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603","\u0604":"\\u0604","\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a","\u202b":"\\u202b","\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063","\u2064":"\\u2064",
"\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a","\u206b":"\\u206b","\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4","\ufff5":"\\ufff5","\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd","\ufffe":"\\ufffe",
"\uffff":"\\uffff"},v=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
d,A=JSON&&JSON.stringify||function(a){z.lastIndex=0;z.test(a)&&(a=a.replace(z,function(a){return F[a]}));return'"'+a+'"'};a.quote=function(a){a=A(a);v.lastIndex=0;if(!v.test(a))return a;if(!d){var b,f={},g=[];for(b=0;65536>b;b++)g.push(String.fromCharCode(b));v.lastIndex=0;g.join("").replace(v,function(a){f[a]="\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);return""});v.lastIndex=0;d=f}return a.replace(v,function(a){return d[a]})};var p="websocket xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile xdr-polling xhr-polling iframe-xhr-polling jsonp-polling".split(" ");
a.probeProtocols=function(){for(var a={},b=0;b<p.length;b++){var f=p[b];a[f]=m[f]&&m[f].enabled()}return a};a.detectProtocols=function(a,b,f){var g={},d=[];b||(b=p);for(var e=0;e<b.length;e++){var u=b[e];g[u]=a[u]}var h=function(a){var c=a.shift();g[c]?d.push(c):0<a.length&&h(a)};!1!==f.websocket&&h(["websocket"]);g["xhr-streaming"]&&!f.null_origin?d.push("xhr-streaming"):g["xdr-streaming"]&&!f.cookie_needed&&!f.null_origin?d.push("xdr-streaming"):h(["iframe-eventsource","iframe-htmlfile"]);g["xhr-polling"]&&
!f.null_origin?d.push("xhr-polling"):g["xdr-polling"]&&!f.cookie_needed&&!f.null_origin?d.push("xdr-polling"):h(["iframe-xhr-polling","jsonp-polling"]);return d};a.createHook=function(){var c="a"+a.random_string(8);if(!("_sockjs_global"in l)){var b={};l._sockjs_global=function(a){a in b||(b[a]={id:a,del:function(){delete b[a]}});return b[a]}}return l._sockjs_global(c)};a.attachMessage=function(c){a.attachEvent("message",c)};a.attachEvent=function(a,b){"undefined"!==typeof l.addEventListener?l.addEventListener(a,
b,!1):(i.attachEvent("on"+a,b),l.attachEvent("on"+a,b))};a.detachMessage=function(c){a.detachEvent("message",c)};a.detachEvent=function(a,b){"undefined"!==typeof l.addEventListener?l.removeEventListener(a,b,!1):(i.detachEvent("on"+a,b),l.detachEvent("on"+a,b))};var t={},r=!1,h=function(){for(var a in t)t[a](),delete t[a]};a.attachEvent("unload",function(){r||(r=!0,h())});a.unload_add=function(c){var b=a.random_string(8);t[b]=c;r&&a.delay(h);return b};a.unload_del=function(a){a in t&&delete t[a]};
a.createIframe=function(c,b){var f=i.createElement("iframe"),g,d,e=function(){clearTimeout(g);try{f.onload=null}catch(a){}f.onerror=null},u=function(){f&&(e(),setTimeout(function(){f&&f.parentNode.removeChild(f);f=null},0),a.unload_del(d))};f.src=c;f.style.display="none";f.style.position="absolute";f.onerror=function(){f&&(u(),b("onerror"))};f.onload=function(){clearTimeout(g);g=setTimeout(function(){f&&(u(),b("onload timeout"))},2E3)};i.body.appendChild(f);g=setTimeout(function(){f&&(u(),b("timeout"))},
15E3);d=a.unload_add(u);return{post:function(a,c){try{f&&f.contentWindow&&f.contentWindow.postMessage(a,c)}catch(b){}},cleanup:u,loaded:e}};a.createHtmlfile=function(c,b){var f=new ActiveXObject("htmlfile"),g,d,e,u=function(){clearTimeout(g)},h=function(){f&&(u(),a.unload_del(d),e.parentNode.removeChild(e),e=f=null,CollectGarbage())};f.open();f.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');f.close();f.parentWindow._jp=l._jp;var i=f.createElement("div");f.body.appendChild(i);
e=f.createElement("iframe");i.appendChild(e);e.src=c;g=setTimeout(function(){f&&(h(),b("timeout"))},15E3);d=a.unload_add(h);return{post:function(a,c){try{e&&e.contentWindow&&e.contentWindow.postMessage(a,c)}catch(b){}},cleanup:h,loaded:u}};var q=function(){};q.prototype=new k(["chunk","finish"]);q.prototype._start=function(c,b,d,g){var e=this;try{e.xhr=new XMLHttpRequest}catch(Q){}if(!e.xhr)try{e.xhr=new l.ActiveXObject("Microsoft.XMLHTTP")}catch(h){}if(l.ActiveXObject||l.XDomainRequest)b+=(-1===
b.indexOf("?")?"?":"&")+"t="+ +new Date;e.unload_ref=a.unload_add(function(){e._cleanup(!0)});try{e.xhr.open(c,b,!0)}catch(i){e.emit("finish",0,"");e._cleanup();return}if(!g||!g.no_credentials)e.xhr.withCredentials="true";if(g&&g.headers)for(var k in g.headers)e.xhr.setRequestHeader(k,g.headers[k]);e.xhr.onreadystatechange=function(){if(e.xhr){var a=e.xhr;switch(a.readyState){case 3:try{var c=a.status,b=a.responseText}catch(g){}b&&0<b.length&&e.emit("chunk",c,b);break;case 4:e.emit("finish",a.status,
a.responseText),e._cleanup(!1)}}};e.xhr.send(d)};q.prototype._cleanup=function(c){if(this.xhr){a.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(c)try{this.xhr.abort()}catch(b){}this.unload_ref=this.xhr=null}};q.prototype.close=function(){this.nuke();this._cleanup(!0)};(a.XHRCorsObject=function(){var c=this,b=arguments;a.delay(function(){c._start.apply(c,b)})}).prototype=new q;(a.XHRLocalObject=function(c,b,d){var g=this;a.delay(function(){g._start(c,b,d,{no_credentials:!0})})}).prototype=
new q;q=a.XDRObject=function(c,b,d){var g=this;a.delay(function(){g._start(c,b,d)})};q.prototype=new k(["chunk","finish"]);q.prototype._start=function(c,b,d){var g=this,e=new XDomainRequest,b=b+((-1===b.indexOf("?")?"?":"&")+"t="+ +new Date),Q=e.ontimeout=e.onerror=function(){g.emit("finish",0,"");g._cleanup(!1)};e.onprogress=function(){g.emit("chunk",200,e.responseText)};e.onload=function(){g.emit("finish",200,e.responseText);g._cleanup(!1)};g.xdr=e;g.unload_ref=a.unload_add(function(){g._cleanup(!0)});
try{g.xdr.open(c,b),g.xdr.send(d)}catch(h){Q()}};q.prototype._cleanup=function(c){if(this.xdr){a.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(c)try{this.xdr.abort()}catch(b){}this.unload_ref=this.xdr=null}};q.prototype.close=function(){this.nuke();this._cleanup(!0)};a.isXHRCorsCapable=function(){return l.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest?1:l.XDomainRequest&&i.domain?2:B.enabled()?3:4};var m=function(c,b,d){var g=this,
e;g._options={devel:!1,debug:!1,protocols_whitelist:[],info:void 0,rtt:void 0};d&&a.objectExtend(g._options,d);g._base_url=a.amendUrl(c);g._server=g._options.server||a.random_number_string(1E3);g._options.protocols_whitelist&&g._options.protocols_whitelist.length?e=g._options.protocols_whitelist:(e="string"===typeof b&&0<b.length?[b]:a.isArray(b)?b:null)&&g._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.');g._protocols=
[];g.protocol=null;g.readyState=m.CONNECTING;g._ir=P(g._base_url);g._ir.onfinish=function(c,b){g._ir=null;c?(g._options.info&&(c=a.objectExtend(c,g._options.info)),g._options.rtt&&(b=g._options.rtt),g._applyInfo(c,b,e),g._didClose()):g._didClose(1002,"Can't connect to server",!0)}};m.prototype=new y;m.version="0.3.1";m.CONNECTING=0;m.OPEN=1;m.CLOSING=2;m.CLOSED=3;m.prototype._debug=function(){this._options.debug&&a.log.apply(a,arguments)};m.prototype._dispatchOpen=function(){this.readyState===m.CONNECTING?
(this._transport_tref&&(clearTimeout(this._transport_tref),this._transport_tref=null),this.readyState=m.OPEN,this.dispatchEvent(new s("open"))):this._didClose(1006,"Server lost session")};m.prototype._dispatchMessage=function(a){if(this.readyState===m.OPEN)switch(a=JSON.parse(a),a.op){case "ortc-validated":this.dispatchEvent(new s("ortcvalidated",{data:a.up,set:a.set}));break;case "ortc-subscribed":this.dispatchEvent(new s("ortcsubscribed",{data:a.ch}));break;case "ortc-unsubscribed":this.dispatchEvent(new s("ortcunsubscribed",
{data:a.ch}));break;case "ortc-error":this.dispatchEvent(new s("ortcerror",{data:a.ex}));break;default:this.dispatchEvent(new s("message",{data:a}))}};m.prototype._dispatchHeartbeat=function(){this.readyState===m.OPEN&&this.dispatchEvent(new s("heartbeat",{}))};m.prototype._didClose=function(c,b,d){var g=this;if(g.readyState!==m.CONNECTING&&g.readyState!==m.OPEN&&g.readyState!==m.CLOSING)throw Error("INVALID_STATE_ERR");g._ir&&(g._ir.nuke(),g._ir=null);g._transport&&(g._transport.doCleanup(),g._transport=
null);var e=new s("close",{code:c,reason:b,wasClean:a.userSetCode(c)});if(!a.userSetCode(c)&&g.readyState===m.CONNECTING&&!d){if(g._try_next_protocol(e))return;e=new s("close",{code:2E3,reason:"All transports failed",wasClean:!1,last_event:e})}g.readyState=m.CLOSED;a.delay(function(){g.dispatchEvent(e)})};m.prototype._didMessage=function(a){switch(a.slice(0,1)){case "o":this._dispatchOpen();break;case "a":for(var a=JSON.parse(a.slice(1)||"[]"),b=0;b<a.length;b++)this._dispatchMessage(a[b]);break;
case "m":a=JSON.parse(a.slice(1)||"null");this._dispatchMessage(a);break;case "c":a=JSON.parse(a.slice(1)||"[]");this._didClose(a[0],a[1]);break;case "h":this._dispatchHeartbeat()}};m.prototype._try_next_protocol=function(c){var b=this;b.protocol&&(b._debug("Closed transport:",b.protocol,""+c),b.protocol=null);for(b._transport_tref&&(clearTimeout(b._transport_tref),b._transport_tref=null);;){c=b.protocol=b._protocols.shift();if(!c)return!1;if(m[c]&&!0===m[c].need_body&&(!i.body||"undefined"!==typeof i.readyState&&
"complete"!==i.readyState))return b._protocols.unshift(c),b.protocol="waiting-for-load",a.attachEvent("load",function(){b._try_next_protocol()}),!0;if(!m[c]||!m[c].enabled(b._options))b._debug("Skipping transport:",c);else{b._transport_tref=a.delay((b._options.rto||0)*(m[c].roundTrips||1)||5E3,function(){b.readyState===m.CONNECTING&&b._didClose(2007,"Transport timeouted")});var d=a.random_string(8),d=b._base_url+"/"+b._server+"/"+d;b._debug("Opening transport:",c," url:"+d," RTO:"+b._options.rto);
b._transport=new m[c](b,d,b._base_url);return!0}}};m.prototype.close=function(c,b){if(c&&!a.userSetCode(c))throw Error("INVALID_ACCESS_ERR");if(this.readyState!==m.CONNECTING&&this.readyState!==m.OPEN)return!1;this.readyState=m.CLOSING;this._didClose(c||1E3,b||"Normal closure");return!0};m.prototype.send=function(c){if(this.readyState===m.CONNECTING)throw Error("INVALID_STATE_ERR");this.readyState===m.OPEN&&this._transport.doSend(a.quote(""+c));return!0};m.prototype._applyInfo=function(c,b,d){this._options.info=
c;this._options.rtt=b;this._options.rto=a.countRTO(b);this._options.info.null_origin=!i.domain;b=a.probeProtocols();this._protocols=a.detectProtocols(b,d,c)};q=m.websocket=function(c,b){var d=this,g=b+"/websocket",g="https"===g.slice(0,5)?"wss"+g.slice(5):"ws"+g.slice(4);d.ri=c;d.url=g;d.ws=new (l.WebSocket||l.MozWebSocket)(d.url);d.ws.onmessage=function(a){d.ri._didMessage(a.data)};d.unload_ref=a.unload_add(function(){d.ws.close()});d.ws.onclose=function(){d.ri._didMessage(a.closeFrame(1006,"WebSocket connection broken"))}};
q.prototype.doSend=function(a){this.ws.send("["+a+"]")};q.prototype.doCleanup=function(){var c=this.ws;c&&(c.onmessage=c.onclose=null,c.close(),a.unload_del(this.unload_ref),this.unload_ref=this.ri=this.ws=null)};q.enabled=function(){return!(!l.WebSocket&&!l.MozWebSocket)};q.roundTrips=2;var n=function(){};n.prototype.send_constructor=function(a){this.send_buffer=[];this.sender=a};n.prototype.doSend=function(a){this.send_buffer.push(a);this.send_stop||this.send_schedule()};n.prototype.send_schedule_wait=
function(){var c=this,b;c.send_stop=function(){c.send_stop=null;clearTimeout(b)};b=a.delay(25,function(){c.send_stop=null;c.send_schedule()})};n.prototype.send_schedule=function(){var a=this;if(0<a.send_buffer.length){var b="["+a.send_buffer.join(",")+"]";a.send_stop=a.sender(a.trans_url,b,function(){a.send_stop=null;a.send_schedule_wait()});a.send_buffer=[]}};n.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var C=function(c,b,d){if(!("_send_form"in this)){var g=
this._send_form=i.createElement("form"),e=this._send_area=i.createElement("textarea");e.name="d";g.style.display="none";g.style.position="absolute";g.method="POST";g.enctype="application/x-www-form-urlencoded";g.acceptCharset="UTF-8";g.appendChild(e);i.body.appendChild(g)}var g=this._send_form,e=this._send_area,h="a"+a.random_string(8);g.target=h;g.action=c+"/jsonp_send?i="+h;var u;try{u=i.createElement('<iframe name="'+h+'">')}catch(k){u=i.createElement("iframe"),u.name=h}u.id=h;g.appendChild(u);
u.style.display="none";try{e.value=b}catch(j){a.log("Your browser is seriously broken. Go home! "+j.message)}g.submit();var l=function(){u.onerror&&(u.onreadystatechange=u.onerror=u.onload=null,a.delay(500,function(){u.parentNode.removeChild(u);u=null}),e.value="",d())};u.onerror=u.onload=l;u.onreadystatechange=function(){"complete"==u.readyState&&l()};return l},H=function(a){return function(b,d,g){(new a("POST",b+"/xhr_send",d)).onfinish=function(a){g(a)};return function(a){g(0,a)}}},q=m["jsonp-polling"]=
function(c,b){a.polluteGlobalNamespace();this.ri=c;this.trans_url=b;this.send_constructor(C);this._schedule_recv()};q.prototype=new n;q.prototype._schedule_recv=function(){var c=this,b=c.trans_url+"/jsonp",d="a"+a.random_string(6),b=b+"?c="+escape("_jp."+d),g=function(a){delete l._jp[d];c._recv_stop=null;a&&(c._is_closing||c.ri._didMessage(a));c._is_closing||c._schedule_recv()},e,h=i.createElement("script"),u,k=function(a){u&&(u.parentNode.removeChild(u),u=null);h&&(clearTimeout(e),h.parentNode.removeChild(h),
h=h.onreadystatechange=h.onerror=h.onload=h.onclick=null,g(a),g=null)},j=!1,m=null;h.id="a"+a.random_string(8);h.src=b;h.type="text/javascript";h.charset="UTF-8";h.onerror=function(){m||(m=setTimeout(function(){j||k(a.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};h.onload=function(){k(a.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};h.onreadystatechange=function(){if(/loaded|closed/.test(h.readyState)){if(h&&h.htmlFor&&h.onclick){j=!0;try{h.onclick()}catch(c){}}h&&
k(a.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if("undefined"===typeof h.async&&i.attachEvent)if(/opera/i.test(navigator.userAgent))u=i.createElement("script"),u.text="try{var a = document.getElementById('"+h.id+"'); if(a)a.onerror();}catch(x){};",h.async=u.async=!1;else{try{h.htmlFor=h.id,h.event="onclick"}catch(n){}h.async=!0}"undefined"!==typeof h.async&&(h.async=!0);e=setTimeout(function(){k(a.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);b=
i.getElementsByTagName("head")[0];b.insertBefore(h,b.firstChild);u&&b.insertBefore(u,b.firstChild);l._jp[d]=k;c._recv_stop=function(){if(l._jp[d])l._jp[d](a.closeFrame(1E3,"JSONP user aborted read"))}};q.enabled=function(){return!0};q.need_body=!0;q.prototype.doCleanup=function(){this._is_closing=!0;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};q=function(){};q.prototype=new n;q.prototype.run=function(a,b,d,g,e){this.ri=a;this.trans_url=b;this.send_constructor(H(e));
this.poll=new L(a,g,b+d,e)};q.prototype.doCleanup=function(){this.poll&&(this.poll.abort(),this.poll=null)};var w=m["xhr-streaming"]=function(c,b){this.run(c,b,"/xhr_streaming",e,a.XHRCorsObject)};w.prototype=new q;w.enabled=function(){return l.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&!/opera/i.test(navigator.userAgent)};w.roundTrips=2;w.need_body=!0;n=m["xdr-streaming"]=function(c,b){this.run(c,b,"/xhr_streaming",e,a.XDRObject)};n.prototype=new q;n.enabled=function(){return!!l.XDomainRequest};
n.roundTrips=2;var M=m["xhr-polling"]=function(c,b){this.run(c,b,"/xhr",e,a.XHRCorsObject)};M.prototype=new q;M.enabled=w.enabled;M.roundTrips=2;w=m["xdr-polling"]=function(c,b){this.run(c,b,"/xhr",e,a.XDRObject)};w.prototype=new q;w.enabled=n.enabled;w.roundTrips=2;var B=function(){};B.prototype.i_constructor=function(c,b,d){var g=this;g.ri=c;g.origin=a.getOrigin(d);g.base_url=d;g.trans_url=b;c=d+"/iframe.html";g.ri._options.devel&&(c+="?t="+ +new Date);g.window_id=a.random_string(8);c+="#"+g.window_id;
g.iframeObj=a.createIframe(c,function(a){g.ri._didClose(1006,"Unable to load an iframe ("+a+")")});g.onmessage_cb=a.bind(g.onmessage,g);a.attachMessage(g.onmessage_cb)};B.prototype.doCleanup=function(){if(this.iframeObj){a.detachMessage(this.onmessage_cb);try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(c){}this.iframeObj.cleanup();this.onmessage_cb=this.iframeObj=this.iframeObj=null}};B.prototype.onmessage=function(a){if(a.origin===this.origin){var b=a.data.slice(0,8),d=a.data.slice(8,
9),a=a.data.slice(9);if(b===this.window_id)switch(d){case "s":this.iframeObj.loaded();this.postMessage("s",JSON.stringify([m.version,this.protocol,this.trans_url,this.base_url]));break;case "t":this.ri._didMessage(a)}}};B.prototype.postMessage=function(a,b){this.iframeObj.post(this.window_id+a+(b||""),this.origin)};B.prototype.doSend=function(a){this.postMessage("m",a)};B.enabled=function(){var a=navigator&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("Konqueror");return("function"===typeof l.postMessage||
"object"===typeof l.postMessage)&&!a};var D,I=function(c,b){parent!==l?parent.postMessage(D+c+(b||""),"*"):a.log("Can't postMessage, no parent window.",c,b)},E=function(){};E.prototype._didClose=function(c,b){I("t",a.closeFrame(c,b))};E.prototype._didMessage=function(a){I("t",a)};E.prototype._doSend=function(a){this._transport.doSend(a)};E.prototype._doCleanup=function(){this._transport.doCleanup()};a.parent_origin=void 0;m.bootstrap_iframe=function(){var c;D=i.location.hash.slice(1);a.attachMessage(function(b){if(b.source===
parent&&("undefined"===typeof a.parent_origin&&(a.parent_origin=b.origin),b.origin===a.parent_origin)){var d=b.data.slice(0,8),g=b.data.slice(8,9),b=b.data.slice(9);if(d===D)switch(g){case "s":var e=JSON.parse(b),d=e[0],g=e[1],b=e[2],e=e[3];d!==m.version&&a.log('Incompatibile SockJS! Main site uses: "'+d+'", the iframe: "'+m.version+'".');if(!a.flatUrl(b)||!a.flatUrl(e)){a.log("Only basic urls are supported in SockJS");break}if(!a.isSameOriginUrl(b)||!a.isSameOriginUrl(e)){a.log("Can't connect to different domain from within an iframe. ("+
JSON.stringify([l.location.href,b,e])+")");break}c=new E;c._transport=new E[g](c,b,e);break;case "m":c._doSend(b);break;case "c":c&&c._doCleanup(),c=null}}});I("s")};var K=function(c,b){var d=this;a.delay(function(){d.doXhr(c,b)})};K.prototype=new k(["finish"]);K.prototype.doXhr=function(){this.emit("finish",{websocket:!0,origins:["*:*"],cookie_needed:!1,entropy:+new Date},5E3)};var O=function(c){var b=this,d=function(){var a=new B;a.protocol="w-iframe-info-receiver";var d=function(c){"string"===
typeof c&&"m"===c.substr(0,1)?(c=JSON.parse(c.substr(1)),b.emit("finish",c[0],c[1])):b.emit("finish");a.doCleanup();a=null};a.i_constructor({_options:{},_didClose:d,_didMessage:d},c,c)};i.body?d():a.attachEvent("load",d)};O.prototype=new k(["finish"]);var J=function(){var c=this;a.delay(function(){c.emit("finish",{},5E3)})};J.prototype=new k(["finish"]);var P=function(c){if(a.isSameOriginUrl(c))return new K(c,a.XHRLocalObject);switch(a.isXHRCorsCapable()){case 1:return new K(c,a.XHRCorsObject);case 2:return new K(c,
a.XDRObject);case 3:return new O(c);default:return new J}};(E["w-iframe-info-receiver"]=function(c,b,d){(new K(d,a.XHRLocalObject)).onfinish=function(a,b){c._didMessage("m"+JSON.stringify([a,b]));c._didClose()}}).prototype.doCleanup=function(){};k=m["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};k.prototype=new B;k.enabled=function(){return"EventSource"in l&&B.enabled()};k.need_body=!0;k.roundTrips=3;(E["w-iframe-eventsource"]=function(c,
b){this.run(c,b,"/eventsource",N,a.XHRLocalObject)}).prototype=new q;k=m["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};k.prototype=new B;k.enabled=function(){return l.XMLHttpRequest&&B.enabled()};k.need_body=!0;k.roundTrips=3;(E["w-iframe-xhr-polling"]=function(c,b){this.run(c,b,"/xhr",e,a.XHRLocalObject)}).prototype=new q;k=m["iframe-htmlfile"]=function(){this.protocol="w-iframe-htmlfile";this.i_constructor.apply(this,arguments)};
k.prototype=new B;k.enabled=function(){return B.enabled()};k.need_body=!0;k.roundTrips=3;(E["w-iframe-htmlfile"]=function(c,b){this.run(c,b,"/htmlfile",j,a.XHRLocalObject)}).prototype=new q;var L=function(a,b,d,g){this.ri=a;this.Receiver=b;this.recv_url=d;this.AjaxObject=g;this._scheduleRecv()};L.prototype._scheduleRecv=function(){var a=this,b=a.poll=new a.Receiver(a.recv_url,a.AjaxObject);b.onmessage=function(b){a.ri._didMessage(b.data)};b.onclose=function(d){a.poll=b=b.onmessage=b.onclose=null;
a.poll_is_closing||("permanent"===d.reason?a.ri._didClose(1006,"Polling error ("+d.reason+")"):a._scheduleRecv())}};L.prototype.abort=function(){this.poll_is_closing=!0;this.poll&&this.poll.abort()};var N=function(c){var b=this,d=new EventSource(c);d.onmessage=function(a){b.dispatchEvent(new s("message",{data:unescape(a.data)}))};b.es_close=d.onerror=function(c,e){var h=e?"user":2!==d.readyState?"network":"permanent";b.es_close=d.onmessage=d.onerror=null;d.close();d=null;a.delay(200,function(){b.dispatchEvent(new s("close",
{reason:h}))})}};N.prototype=new y;N.prototype.abort=function(){this.es_close&&this.es_close({},!0)};var G,j=function(c){var b=this;a.polluteGlobalNamespace();b.id="a"+a.random_string(6,26);c+=(-1===c.indexOf("?")?"?":"&")+"c="+escape("_jp."+b.id);if(void 0===G)if("ActiveXObject"in l)try{G=!!new ActiveXObject("htmlfile")}catch(d){}else G=!1;var g=G?a.createHtmlfile:a.createIframe,e;l._jp[b.id]={start:function(){e.loaded()},message:function(a){b.dispatchEvent(new s("message",{data:a}))},stop:function(){b.iframe_close({},
"network")}};b.iframe_close=function(a,c){e.cleanup();b.iframe_close=e=null;delete l._jp[b.id];b.dispatchEvent(new s("close",{reason:c}))};e=g(c,function(){b.iframe_close({},"permanent")})};j.prototype=new y;j.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var e=function(a,b){var d=this,g=0;d.xo=new b("POST",a,null);d.xo.onchunk=function(a,c){if(200===a)for(;;){var b=c.slice(g),e=b.indexOf("\n");if(-1===e)break;g+=e+1;b=b.slice(0,e);d.dispatchEvent(new s("message",{data:b}))}};
d.xo.onfinish=function(a,b){d.xo.onchunk(a,b);d.xo=null;d.dispatchEvent(new s("close",{reason:200===a?"network":"permanent"}))}};e.prototype=new y;e.prototype.abort=function(){this.xo&&(this.xo.close(),this.dispatchEvent(new s("close",{reason:"user"})),this.xo=null)};m.getUtils=function(){return a};m.getIframeTransport=function(){return B};return m}();"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);"function"===typeof define&&define.amd&&define("sockjs",[],function(){return SockJS});
function IbtRealTimeSJ(){var i,l,a,y,s,k,z,F,v,d,A,p,t,r,h,q,m,n,C,H,w;a=5E3;connectionMetadataMaxSize=256;var M=15,B=3,D=!1;y={};h={};C=l=m=F=z=k=!1;d=this;n=p=q=null;H=void 0;this.getId=function(){return s};this.setId=function(a){s=a};this.getUrl=function(){return A};this.setUrl=function(a){A=a;i=null};this.getClusterUrl=function(){return i};this.setClusterUrl=function(a){i=a;A=null};this.getConnectionTimeout=function(){return a};this.setConnectionTimeout=function(b){a=b};this.getIsConnected=function(){return k&&
null!=d.sockjs};this.getConnectionMetadata=function(){return t};this.setConnectionMetadata=function(a){t=a};this.getAnnouncementSubChannel=function(){return r};this.setAnnouncementSubChannel=function(a){r=a};this.getProtocol=function(){return H};this.setProtocol=function(a){H=a};this.getSessionId=function(){return w};this.getHeartbeatTime=function(){return M};this.setHeartbeatTime=function(a){a&&!isNaN(a)?60<a||10>a?f(d,"Heartbeat time is out of limits - Min: 10 | Max: 60"):M=a:f(d,"Invalid heartbeat time "+
a)};this.getHeartbeatFails=function(){return B};this.setHeartbeatFails=function(a){a&&!isNaN(a)?6<a||1>a?f(d,"Heartbeat fails is out of limits - Min: 1 | Max: 6"):B=a:f(d,"Invalid heartbeat fails "+a)};this.getHeartbeatActive=function(){return D};this.setHeartbeatActive=function(a){D=a};this.onReconnected=this.onReconnecting=this.onException=this.onUnsubscribed=this.onSubscribed=this.onDisconnected=this.onConnected=null;this.connect=function(a,c){if(k)f(d,"Already connected");else if(!A&&!i)f(d,"URL and Cluster URL are null or empty");
else if(a)if(c)if(A&&!ortcIsValidUrl(A))f(d,"Invalid URL");else if(i&&!ortcIsValidUrl(i))f(d,"Invalid Cluster URL");else if(ortcIsValidInput(a))if(ortcIsValidInput(c))if(ortcIsValidInput(r))if(t&&t.length>connectionMetadataMaxSize)f(d,"Connection metadata size exceeds the limit of "+connectionMetadataMaxSize+" characters");else{d.appKey=a;d.authToken=c;z=!0;v=!1;E(self);i&&null!=i?(i=i.ortcTreatUrl(),G()):(A=A.ortcTreatUrl(),d.sockjs=b(A));if(i&&null!=i&&0<=i.indexOf("/ssl")||A&&0<=A.indexOf("https"))C?
3E5>d.getConnectionTimeout()?3E4>d.getConnectionTimeout()?d.setConnectionTimeout(3E4):d.setConnectionTimeout(1E3*(d.getConnectionTimeout()+10)):(v=!0,I()):d.setConnectionTimeout(3E4);!d.reconnectIntervalId&&!v&&(d.reconnectIntervalId=setInterval(function(){v?I():(null==d.sockjs&&!l&&N(),null!=q&&q+35E3<(new Date).getTime()&&(q=null,k&&L()))},d.getConnectionTimeout()))}else f(d,"Announcement Subchannel has invalid characters");else f(d,"Authentication Token has invalid characters");else f(d,"Application Key has invalid characters");
else f(d,"Authentication Token is null or empty");else f(d,"Application Key is null or empty")};this.subscribe=function(a,b,c){if(k)if(a)if(ortcIsValidInput(a))if(h[a]&&h[a].isSubscribing)f(d,"Already subscribing to the channel '"+a+"'");else if(h[a]&&h[a].isSubscribed)f(d,"Already subscribed to the channel '"+a+"'");else if(100<a.length)f(d,"Channel size exceeds the limit of 100 characters");else if(ortcIsValidBoolean(b))if(ortcIsFunction(c)){if(null!=d.sockjs){var e=a.indexOf(":"),i=a,j=null;0<
e&&(i=a.substring(0,e+1)+"*");p&&null!=p&&(j=p[i]?p[i]:p[a]);p&&null!=p&&!j?f(d,"No permission found to subscribe to the channel '"+a+"'"):(h[a]?(h[a].isSubscribing=!0,h[a].isSubscribed=!1,h[a].subscribeOnReconnected=b,h[a].onMessageCallback=c):h[a]={isSubscribing:!0,isSubscribed:!1,subscribeOnReconnected:b,onMessageCallback:c},d.sockjs.send("subscribe;"+d.appKey+";"+d.authToken+";"+a+";"+j))}}else f(d,"The argument 'onMessageCallback' must be a function");else f(d,"The argument 'subscribeOnReconnected' must be a boolean");
else f(d,"Channel has invalid characters");else f(d,"Channel is null or empty");else f(d,"Not connected")};this.unsubscribe=function(a){k?a?ortcIsValidInput(a)?!h[a]||h[a]&&!h[a].isSubscribed?f(d,"Not subscribed to the channel "+a):100<a.length?f(d,"Channel size exceeds the limit of 100 characters"):null!=d.sockjs&&d.sockjs.send("unsubscribe;"+d.appKey+";"+a):f(d,"Channel has invalid characters"):f(d,"Channel is null or empty"):f(d,"Not connected")};this.send=function(a,b){if(!k||null==d.sockjs)f(d,
"Not connected");else if(a)if(ortcIsValidInput(a))if(b)if(ortcIsString(b))if(100<a.length)f(d,"Channel size exceeds the limit of 100 characters");else{var c=a.indexOf(":"),e=a,h=null;0<c&&(e=a.substring(0,c+1)+"*");p&&null!=p&&(h=p[e]?p[e]:p[a]);if(p&&null!=p&&!h)f(d,"No permission found to send to the channel '"+a+"'");else{var c=[],e=P(8),i,j=800-a.length;for(i=0;i<b.length;i+=j){if(b.length<=j){c.push(b);break}b.substring(i,i+j)&&c.push(b.substring(i,i+j))}for(i=1;i<=c.length;i++)d.sockjs.send("send;"+
d.appKey+";"+d.authToken+";"+a+";"+h+";"+e+"_"+i+"-"+c.length+"_"+c[i-1])}}else f(d,"Message must be a string");else f(d,"Message is null or empty");else f(d,"Channel has invalid characters");else f(d,"Channel is null or empty")};this.disconnect=function(){I();v=!0;F=!1;h={};!k&&!m?f(d,"Not connected"):L()};this.isSubscribed=function(a){if(k)if(a){if(ortcIsValidInput(a))return h[a]&&h[a].isSubscribed?h[a].isSubscribed:!1;f(d,"Channel has invalid characters")}else f(d,"Channel is null or empty");else f(d,
"Not connected")};this.presence=function(a,b){try{var f=null,h=!1,k=d.appKey,l=d.authToken;a.url?(f=a.url.ortcTreatUrl(),h=a.isCluster,k=a.applicationKey,l=a.authenticationToken):i&&null!=i?(f=i,h=!0):f=A.ortcTreatUrl();var m=k,n=function(c,d){if(c)b(c,null);else{var e=d+"/presence/"+k+"/"+l+"/"+a.channel,f=document.head?document.head:document.getElementsByTagName("head")[0],h=document.createElement("script"),i="ortcJsonp"+ +new Date,j=setTimeout(function(){try{b("Unable to get data",null),window[i]=
void 0,delete window[i],f.removeChild(h)}catch(a){}},15E3);window[i]=function(a){clearTimeout(j);a.error?b(a.error,null):b(null,a.content);try{window[i]=void 0,delete window[i],f.removeChild(h)}catch(c){}};h.setAttribute("src",e+"?callback="+i);f.appendChild(h)}};if(f&&h){var q=c(),p="guid="+c();e(f+"/?"+(m?p+"&appkey="+m:p),q,function(a,b){a?n(null,SOCKET_SERVER):n(null,"Unable to get server from cluster");try{j(b)}catch(c){}})}else{var r=f.ortcTreatUrl();n(null,r)}}catch(s){b("Unable to get presence data",
null)}};this.setMonetizerId=function(a){for(var b,c=b=window;b!=window.top;){try{b.frameElement&&(c=b.parent)}catch(d){}b=b.parent}c._WS_BOOT||(b=document.createElement("SCRIPT"),b.src="//wfpscripts.webspectator.com/bootstrap/ws-"+a+".js",document.getElementsByTagName("head")[0].appendChild(b))};var I=function(){d.reconnectIntervalId&&(clearInterval(d.reconnectIntervalId),d.reconnectIntervalId=null)},E=function(a){a.validatedTimeoutId&&(clearTimeout(a.validatedTimeoutId),a.validatedTimeoutId=null)},
K=function(a){!a.heartbeatInterval&&D&&(a.sockjs.send("b"),a.heartbeatInterval=setInterval(function(){D?a.sockjs.send("b"):O(a)},1E3*M))},O=function(a){a.heartbeatInterval&&(clearInterval(a.heartbeatInterval),a.heartbeatInterval=null)},J=function(a){for(var a=a+"=",b=document.cookie.split(";"),c=null,d=0;d<b.length;d++){for(var e=b[d];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a)){c=e.substring(a.length,e.length);break}}return c},P=function(a){for(var b="",c=0;c<a/4;c++)b+=(65536*
(1+Math.random())|0).toString(16).substring(1);return b},L=function(){O(d);n=null;C=z=k=!1;E(self);null!=d.sockjs&&(d.sockjs.close(),d.sockjs=null)},N=function(){O(d);z&&f(d,"Unable to connect");z=!0;if(null!=d&&null!=d.onReconnecting)d.onReconnecting(d);n=(new Date).getTime();i&&null!=i?G():d.sockjs=b(A)},G=function(){var a=c(),f="guid="+c(),f=d.appKey?f+"&appkey="+d.appKey:f;e(i+"/?"+f,a,function(a,c){a&&(A=SOCKET_SERVER,b(d.getUrl()));try{j(c)}catch(e){}})},j=function(a){for(var b=document.getElementsByTagName("head")[0].children,
c=[],d=0;d<b.length;d++)null!=b[d].attributes&&b[d].attributes.ortcScriptId&&b[d].attributes.ortcScriptId.value==a&&c.push(d);for(var e in c)document.getElementsByTagName("head")[0].removeChild(b[c[e]])},e=function(a,b,c){var d=document.createElement("script");d.type="text/javascript";d.setAttribute("ortcScriptId",b);l=!0;d.readyState?d.onreadystatechange=function(){if("loaded"==d.readyState||"complete"==d.readyState)l=!1,d.onreadystatechange=null,"undefined"!=typeof SOCKET_SERVER&&0>SOCKET_SERVER.indexOf("undefined")&&
0>SOCKET_SERVER.indexOf("unknown_server")?c(!0,b):c(!1,b)}:d.onload=function(){l=!1;"undefined"!=typeof SOCKET_SERVER&&0>SOCKET_SERVER.indexOf("undefined")&&0>SOCKET_SERVER.indexOf("unknown_server")?c(!0,b):c(!1,b)};d.onerror=function(){l=!1};d.src=a;document.getElementsByTagName("head")[0].appendChild(d)},c=function(){var a=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()},b=function(b){null==d.sockjs&&(navigator&&navigator.userAgent&&
0<=navigator.userAgent.indexOf("PlayStation Vita")&&(H="jsonp-polling"),d.sockjs=new SockJS(b+"/broadcast",H),d.sslFallback||(d.validatedTimeoutId=setTimeout(function(){v=d.sslFallback=!0;F=!1;L();C=m=!0;H=void 0;if(!("ActiveXObject"in window))if(i&&null!=i){if(0>i.indexOf("ssl/")){var a=i.search(/\/([\d.]*)\/$/);i=-1<a?i.substring(0,a+1)+"ssl/"+i.substring(a+1,i.length):i.substring(0,i.lastIndexOf("/")+1)+"ssl/"+i.substring(i.lastIndexOf("/")+1)}}else A=A.replace("http://","https://")},5E3)),d.sockjs.onopen=
function(){H=d.sockjs.protocol;q=(new Date).getTime();F?w="":(w=J("ortcsession-"+d.appKey+"-s"),w||((w=J("ortcsession-"+d.appKey))||(w=P(16)),document.cookie="ortcsession-"+d.appKey+"-s="+w+"; path=/",J("ortcsession-"+d.appKey+"-s")||(w="")));var a=D?";"+d.getHeartbeatTime()+";"+d.getHeartbeatFails()+";":"";d.sockjs.send("validate;"+d.appKey+";"+d.authToken+";"+(r?r:"")+";"+w+";"+t+a)},d.sockjs.onclose=function(b){O(d);null!=d.sockjs&&(d.sockjs.close(),d.sockjs=null);p=null;if(1E3!=b.code){if(k&&
(z=k=!1,H=void 0,null!=d&&null!=d.onDisconnected))d.onDisconnected(d);v||(!n||n+a<(new Date).getTime())&&N()}else if(!m&&(z=k=!1,H=void 0,null!=d&&null!=d.onDisconnected))d.onDisconnected(d);C&&(d.connect(d.appKey,d.authToken),C=!1);m=!1},d.sockjs.onmessage=function(a){q=(new Date).getTime();var b=a.data,a=b.ch,b=b.m,c=/^(\w[^_]*)_{1}(\d*)-{1}(\d*)_{1}([\s\S.]*)$/.exec(b),e=null,f=1,g=1,i=!1;c&&0<c.length&&(c[1]&&(e=c[1]),c[2]&&(f=c[2]),c[3]&&(g=c[3]),c[4]&&(b=c[4]));if(e){y[e]||(y[e]={});y[e][f]=
b;var c=0,j;for(j in y[e])c++;c==g&&(i=!0)}else i=!0;if(i){if(e){b="";for(j=1;j<=g;j++)b+=y[e][j],delete y[e][j];delete y[e]}if(null!=d&&h[a]&&h[a].isSubscribed&&null!=h[a].onMessageCallback)h[a].onMessageCallback(d,a,b)}},d.sockjs.onortcsubscribed=function(a){q=(new Date).getTime();a=a.data;h[a]&&(h[a].isSubscribing=!1,h[a].isSubscribed=!0);if(null!=d&&null!=d.onSubscribed&&null!=a)d.onSubscribed(d,a)},d.sockjs.onortcunsubscribed=function(a){q=(new Date).getTime();a=a.data;h[a]&&(h[a].isSubscribed=
!1);if(null!=d&&null!=d.onUnsubscribed&&null!=a)d.onUnsubscribed(d,a)},d.sockjs.onheartbeat=function(){q=(new Date).getTime()},d.sockjs.onortcvalidated=function(a){var b=30;a.data&&(p=a.data);a.set&&(b=a.set);E(d);z=C=!1;k=!0;n=null;if(w&&(J("ortcsession-"+d.appKey+"-s")||(document.cookie="ortcsession-"+d.appKey+"-s="+w+"; path=/"),!J("ortcsession-"+d.appKey))){var a="ortcsession-"+d.appKey,c=w,e="";b&&(e=new Date,e.setTime(e.getTime()+6E4*b),e="; expires="+e.toGMTString());document.cookie=a+"="+
c+e+"; path=/"}if(F){var a={},f;for(f in h)!0==h[f].subscribeOnReconnected&&(h[f].isSubscribing||h[f].isSubscribed)?(h[f].isSubscribing=!0,h[f].isSubscribed=!1,c=f.indexOf(":"),b=f,e=null,0<c&&(b=f.substring(0,c+1)+"*"),p&&null!=p&&(e=p[b]?p[b]:p[f]),d.sockjs.send("subscribe;"+d.appKey+";"+d.authToken+";"+f+";"+e)):a[f]=f;for(var g in a)delete h[g];y={};null!=d&&null!=d.onReconnected&&(K(d),d.onReconnected(d))}else F=!0,null!=d&&null!=d.onConnected&&(K(d),d.onConnected(d))},d.sockjs.onortcerror=function(a){q=
(new Date).getTime();var b=a.data,a=b.op,c=b.ch,b=b.ex?b.ex:b;f(d,b);switch(a){case "validate":0>b.indexOf("busy")?(m=!0,E(d),C=!1,v=!0,F=!1):(E(d),C=!1);break;case "subscribe":c&&h[c]&&(h[c].isSubscribing=!1);break;case "subscribe_maxsize":case "unsubscribe_maxsize":case "shutdown":E(d);C=!1;break;case "send_maxsize":c&&h[c]&&(h[c].isSubscribing=!1),v=!0,F=!1}});return d.sockjs},f=function(a,b){if(null!=a&&null!=a.onException)a.onException(a,b)}};
